import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const edosz = localFont({
  src: "fonts/edosz.ttf",
  variable: "--font-edosz-mono",
  weight: "100 900",
});

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "900", "400", "700"],
  subsets: ["latin", "cyrillic"],
});

const merriWeather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${edosz.variable} ${merriWeather.variable} antialiased`}
        suppressHydrationWarning
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
